version: 0.2

phases:
  install:
    commands:
      - yum install -y gcc-c++ make
      - curl -sL https://rpm.nodesource.com/setup_12.x | bash -
      - yum install -y nodejs
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build