version: 0.2
phases:
  install:
    commands:
      - yum install -y gcc-c++ make
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
