version: 0.2

phases:
  install:
    commands:
      dnf module install nodejs:12
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build